services:
  postgres:
    image: postgres:14.15-alpine
    container_name: db-modeling-3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGTZ: Asia/Tokyo
    ports:
      - "5436:5432"
    volumes:
      - document_data:/var/lib/postgresql/data

volumes:
  document_data:
