version: '3.8'

services:
  postgres:
    image: postgres:14.15-alpine
    container_name: db-modeling-1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
